# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Noah"
license = "MIT"
licenselink = "https://github.com/nmasur/nmasur.github.io/blob/master/themes/noah/LICENSE"
description = "My personal theme"
homepage = "https://github.com/nmasur/nmasur.github.io"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Noah Masur"
  homepage = "https://noah.masu.rs/"

# If porting an existing theme
# [original]
#   name = ""
#   homepage = ""
#   repo = ""
